module.exports = {
  'AS THEY SAY IN CANADA PEACE OUT - AUDIO FROM JAYUZUMI.COM': require('./AS THEY SAY IN CANADA PEACE OUT - AUDIO FROM JAYUZUMI.COM.mp3'),
  'OH YEAH 1 - AUDIO FROM JAYUZUMI.COM': require('./OH YEAH 1 - AUDIO FROM JAYUZUMI.COM.mp3'),
  'They ask you how you are and you just have to say that you re fine Sound Effect': require('./They ask you how you are and you just have to say that you re fine Sound Effect.mp3'),
  'Star Wars- The Imperial March (Darth Vader s Theme)': require('./Star Wars- The Imperial March (Darth Vader s Theme).mp3'),
  'AINT NOBODY GOT TIME FOR THAT - AUDIO FROM JAYUZUMI.COM': require('./AINT NOBODY GOT TIME FOR THAT - AUDIO FROM JAYUZUMI.COM.mp3'),
  'I know its not a popular opinion by thats my 2 cents': require('./I know its not a popular opinion by thats my 2 cents.mp3'),
  'Voicy_Borat High five': require('./Voicy_Borat High five.mp3'),
  'Voicy_Borat Nice': require('./Voicy_Borat Nice.mp3'),
  'Bruh - Sound Effect - SES': require('./Bruh - Sound Effect - SES.mp3'),
  'Borat wawa we wa It s a very NICE - [Sound Effects]': require('./Borat wawa we wa It s a very NICE - [Sound Effects].mp3'),
  'Homer Simpson ‘Doh’ Sound Effects - SES': require('./Homer Simpson ‘Doh’ Sound Effects - SES.mp3'),
  'Homer Simpson woohoo║Gaming Sound Effect': require('./Homer Simpson woohoo║Gaming Sound Effect.mp3'),
  'JUST DO IT - AUDIO FROM JAYUZUMI.COM': require('./JUST DO IT - AUDIO FROM JAYUZUMI.COM.mp3'),
  'El Risitas': require('./El Risitas.mp3'),
  'DJ DROP THAT BEAT - AUDIO FROM JAYUZUMI.COM': require('./DJ DROP THAT BEAT - AUDIO FROM JAYUZUMI.COM.mp3'),
  'ANOTHER ONE - AUDIO FROM JAYUZUMI.COM': require('./ANOTHER ONE - AUDIO FROM JAYUZUMI.COM.mp3'),
  'NO IDEA WHAT YOURE TALKING ABOUT - AUDIO FROM JAYUZUMI.COM': require('./NO IDEA WHAT YOU\'RE TALKING ABOUT - AUDIO FROM JAYUZUMI.COM.mp3'),
  'Bubb Rubb and Lil Sis Tha whistles go WOOO ': require('./Bubb Rubb and Lil Sis Tha whistles go WOOO .mp3'),
  'IM RICK JAMES - AUDIO FROM JAYUZUMI.COM': require('./IM RICK JAMES - AUDIO FROM JAYUZUMI.COM.mp3'),
  'LET ME ASK YOU SOMETHING - AUDIO FROM JAYUZUMI.COM': require('./LET ME ASK YOU SOMETHING - AUDIO FROM JAYUZUMI.COM.mp3'),
  'YEAH YER YER YER (agree) - AUDIO FROM JAYUZUMI.COM': require('./YEAH YER YER YER (agree) - AUDIO FROM JAYUZUMI.COM.mp3'),
  'Popular Meme Sound Effects (For Video Editing)': require('./Popular Meme Sound Effects (For Video Editing).mp3'),
  'Zombie Kid Likes Turtles': require('./Zombie Kid Likes Turtles.mp3'),
  'Humiliation - Sound Effect - SES': require('./Humiliation - Sound Effect - SES.mp3'),
  'Why Can t We Be Friends': require('./Why Can t We Be Friends.mp3'),
  'Homer Simpson Scream': require('./Homer Simpson Scream.mp3'),
  'James Brown - The Boss': require('./James Brown - The Boss.mp3'),
  'Boring - Homer Simpson Sound Effect - SES': require('./Boring - Homer Simpson Sound Effect - SES.mp3'),
  'NO GOD PLEASE NO': require('./NO GOD PLEASE NO.mp3'),
  'WUBBA LUBBA DUB DUB - AUDIO FROM JAYUZUMI.COM': require('./WUBBA LUBBA DUB DUB - AUDIO FROM JAYUZUMI.COM.mp3'),
  'STRANGER THINGS THEME SONG - AUDIO FROM JAYUZUMI.COM': require('./STRANGER THINGS THEME SONG - AUDIO FROM JAYUZUMI.COM.mp3'),
  'The Full Postgame Interview Bart Scott Flies Over To Sal Paolantonio after Jets Win': require('./The Full Postgame Interview Bart Scott Flies Over To Sal Paolantonio after Jets Win.mp3'),
  'OhHiMark': require('./OhHiMark.mp3'),
  'The Stars and Stripes Forever - With Lyrics': require('./The Stars and Stripes Forever - With Lyrics.mp3'),
  'SMG4 SOUND EFFECTS - ITS JUST A PRANK BRO': require('./SMG4 SOUND EFFECTS - ITS JUST A PRANK BRO.mp3'),
  'CARDI B OMG WHAT IS THAT - AUDIO FROM JAYUZUMI.COM': require('./CARDI B OMG WHAT IS THAT - AUDIO FROM JAYUZUMI.COM.mp3'),
  'Voicy_Borat I like you do you like me': require('./Voicy_Borat I like you do you like me.mp3'),
  'HA GAY - AUDIO FROM JAYUZUMI.COM': require('./HA GAY - AUDIO FROM JAYUZUMI.COM.mp3'),
  'DJ Airhorn Sound Effect': require('./DJ Airhorn Sound Effect.mp3'),
  'OH YEAH 2 - AUDIO FROM JAYUZUMI.COM': require('./OH YEAH 2 - AUDIO FROM JAYUZUMI.COM.mp3'),
  'Voicy_Borat Is nice': require('./Voicy_Borat Is nice.mp3'),
  'Best Cry Ever': require('./Best Cry Ever.mp3'),
  'Voicy_Borat Hello thank you to speak me': require('./Voicy_Borat Hello thank you to speak me.mp3'),
  'COCAINES HELLAVUH DRUG - AUDIO FROM JAYUZUMI.COM': require('./COCAINES HELLAVUH DRUG - AUDIO FROM JAYUZUMI.COM.mp3'),
  'Voicy_Borat Wah wah we wah': require('./Voicy_Borat Wah wah we wah.mp3'),
  'Borat Great Success': require('./Borat Great Success.mp3'),
  'Clapping Sound Effects': require('./Clapping Sound Effects.mp3'),
  'Antoine Dodson ‘Hide Yo Kids, Hide Yo Wife’ Interview (Original)': require('./Antoine Dodson ‘Hide Yo Kids, Hide Yo Wife’ Interview (Original).mp3'),
  'EXCELLENT - Mr Burns': require('./EXCELLENT - Mr Burns.mp3'),
  'Sad Violin Sound Effect - SES': require('./Sad Violin Sound Effect - SES.mp3'),
  'FUCK YO COUCH - AUDIO FROM JAYUZUMI.COM': require('./FUCK YO COUCH - AUDIO FROM JAYUZUMI.COM.mp3'),
  '‘How Dare You’ Greta Thunberg Sound Effect - SES': require('./‘How Dare You’ Greta Thunberg Sound Effect - SES.mp3'),
  'ARE YOU JOKING ME - AUDIO FROM JAYUZUMI.COM': require('./ARE YOU JOKING ME - AUDIO FROM JAYUZUMI.COM.mp3'),
  'WOW - Eddy Wally (Sound Effect HD)': require('./WOW - Eddy Wally (Sound Effect HD).mp3'),
  'Boom goes the dynamite': require('./Boom goes the dynamite.mp3'),
  'BYE - AUDIO FROM JAYUZUMI.COM': require('./BYE - AUDIO FROM JAYUZUMI.COM.mp3'),
  'OBIWAN HELLO THERE - AUDIO FROM JAYUZUMI.COM': require('./OBIWAN HELLO THERE - AUDIO FROM JAYUZUMI.COM.mp3'),
  '2 HOURS LATER - AUDIO FROM JAYUZUMI.COM': require('./2 HOURS LATER - AUDIO FROM JAYUZUMI.COM.mp3'),
  'I m in danger - Simpsons - Ralph Wiggum': require('./I m in danger - Simpsons - Ralph Wiggum.mp3'),
  'Nope SOUND EFFECT': require('./Nope SOUND EFFECT.mp3'),
  'TYT I m Sorry Sound Effects': require('./TYT I m Sorry Sound Effects.mp3'),
  'AND THATS WHY I ALWAYS SAY shlum slum shlippidy dap - AUDIO FROM JAYUZUMI.COM': require('./AND THAT\'S WHY I ALWAYS SAY shlum slum shlippidy dap - AUDIO FROM JAYUZUMI.COM.mp3'),
  'Britney Spears - Toxic (Official HD Video)': require('./Britney Spears - Toxic (Official HD Video).mp3'),
  'Voicy_Borat I is good': require('./Voicy_Borat I is good.mp3'),
  'EVERYTHINGS GONNA BE FINE - AUDIO FROM JAYUZUMI.COM': require('./EVERYTHINGS GONNA BE FINE - AUDIO FROM JAYUZUMI.COM.mp3'),
}
